In [1]:
import os
os.chdir("../")

In [2]:
from crawler.Tv_loader import TvDatafeed,Interval
import os, time
import pandas as pd

os.environ['TZ'] = 'Asia/Ho_Chi_Minh'
time.tzset()    

def load_data_direct(ticker, exchange = "", interval = "1D"):
    username = 'thanhtrunghuynh93'
    password = '@Manutd93@'
    crawler=TvDatafeed(username, password, chromedriver_path="chromedriver")
    if interval == "1D":
        df = crawler.get_hist(symbol=ticker,exchange=exchange,interval=Interval.in_daily, n_bars = 5000)
    if interval == "1W":
        df = crawler.get_hist(symbol=ticker,exchange=exchange,interval=Interval.in_weekly, n_bars = 5000)
    df["ticker"] = ticker
    return df

In [3]:
df = load_data_direct("VNINDEX")

In [5]:
df[-2500:]

,symbol,open,high,low,close,volume,ticker
datetime,,,,,,,
2015-07-27 09:00:00,VNINDEX,629.67999,636.84003,629.41998,635.46002,0,VNINDEX
2015-07-28 09:00:00,VNINDEX,636.58002,639.53998,631.46997,631.46997,0,VNINDEX
2015-07-29 09:00:00,VNINDEX,632.00000,634.64001,624.70001,624.70001,0,VNINDEX
2015-07-30 09:00:00,VNINDEX,625.46002,627.10999,622.42999,626.57001,0,VNINDEX
2015-07-31 09:00:00,VNINDEX,628.31000,629.96997,621.06000,621.06000,0,VNINDEX
...,...,...,...,...,...,...,...
2025-07-21 09:00:00,VNINDEX,1497.28000,1511.96000,1481.37000,1485.05000,0,VNINDEX
2025-07-22 09:00:00,VNINDEX,1485.05000,1509.54000,1476.61000,1509.54000,0,VNINDEX
2025-07-23 09:00:00,VNINDEX,1509.54000,1523.37000,1507.14000,1512.31000,0,VNINDEX
2025-07-24 09:00:00,VNINDEX,1512.31000,1525.32000,1502.82000,1521.02000,0,VNINDEX
2025-07-25 09:00:00,VNINDEX,1521.02000,1533.95000,1519.79000,1533.61000,0,VNINDEX

In [17]:
df_year = df.groupby(df.index.year).agg({"open":"first", "close": "last", "high": "max", "low": "min"})

In [21]:
df_year["volatility"] = (1 / np.sqrt(4 * np.log(2))) * \
    np.log(df_year['high'] / df_year['low'])

In [25]:
df_year["return"] = (df_year["close"] - df_year["open"]) / df_year["close"]

In [26]:
df_year

,open,close,high,low,volatility,return
datetime,,,,,,
2005,243.550003,307.500000,325.250000,242.850006,0.175454,0.207967
2006,306.859985,751.770020,815.979980,304.230011,0.592517,0.591817
2007,751.039978,927.020020,1179.319946,741.270020,0.278858,0.189834
2008,925.659973,315.619995,926.010010,284.059998,0.709683,-1.932831
2009,312.489990,494.769989,633.210022,234.660004,0.596156,0.368414
2010,501.739990,484.660004,551.400024,419.980011,0.163505,-0.035241
2011,485.720001,351.549988,529.200012,346.480011,0.254362,-0.381653
2012,351.369995,413.730010,492.440000,332.279999,0.236258,0.150726
2013,415.500000,504.630000,533.150020,413.679990,0.152368,0.176624
2014,505.609990,545.630000,644.560000,503.040010,0.148878,0.073346
2015,545.429990,579.030030,641.060000,511.130000,0.136027,0.058028
2016,579.030030,664.870000,692.169980,513.820010,0.178942,0.129108
2017,665.919980,984.239990,990.099980,665.429990,0.238647,0.323417
2018,986.049990,892.539980,1211.340000,880.849980,0.191336,-0.104768
2019,900.099980,960.989990,1028.970000,861.849980,0.106439,0.063362
2020,960.260010,1103.870000,1108.830000,649.099980,0.321585,0.130097
2021,1113.770000,1498.280000,1511.680100,998.330020,0.249169,0.256634
2022,1508.480000,1007.090000,1536.450000,873.780030,0.338957,-0.497860
2023,1007.090000,1129.930100,1255.110000,1007.090000,0.132218,0.108715
2024,1129.930100,1266.780000,1306.010000,1128.319900,0.087830,0.108030
2025,1266.780000,1533.610000,1533.950000,1073.610000,0.214292,0.173988

In [28]:
(df_year["return"] - 0.08) / df_year["volatility"]

datetime
2005    0.729350
2006    0.863801
2007    0.393872
2008   -2.836239
2009    0.483789
2010   -0.704818
2011   -1.814940
2012    0.299361
2013    0.634150
2014   -0.044691
2015   -0.161526
2016    0.274434
2017    1.019990
2018   -0.965676
2019   -0.156317
2020    0.155781
2021    0.708894
2022   -1.704816
2023    0.217177
2024    0.319135
2025    0.438599
dtype: float64

In [9]:
daily_returns = df["close"].pct_change().dropna().values

In [10]:
daily_returns

array([ 0.00135586, -0.00217462,  0.00020561, ...,  0.001835  ,
        0.0057594 ,  0.00827734], shape=(4999,))

In [12]:
import numpy as np

In [13]:
# Annualized Sharpe Ratio
risk_free_rate_annual = 0.06   # e.g., 5%
risk_free_rate_daily = risk_free_rate_annual / 252

excess_daily_returns = daily_returns - risk_free_rate_daily
sharpe_ratio = np.mean(excess_daily_returns) / np.std(daily_returns, ddof=1)
annualized_sharpe = sharpe_ratio * np.sqrt(252)

print("Annualized Sharpe Ratio:", annualized_sharpe)

Annualized Sharpe Ratio: 0.25905210725657124